
[browser]
serverAddress = "0.0.0.0"
serverPort = 8501

[server]
address = "0.0.0.0"
port = 8501

[theme]
primaryColor = "#0E76A8"                
backgroundColor = "#FFFFFF"             
secondaryBackgroundColor = "#F5F7FA"    
textColor = "#262730"                   
font = "sans serif"
